language: node_js
node_js:
  - 9
cache:
  directories:
    - node_modules
script:
  - npm test
  - npm run build
deploy:
  provider: pages
  skip-cleanup: true
  github-token: $GITHUB_TOKEN
  keep-history: true
  local-dir: build
  committer-from-gh: true
  on:
    branch: master
branches:
  only:
  - master